/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package xylixlike;

import javafx.application.Application;
import javafx.scene.Scene;
import javafx.scene.layout.Pane;
import javafx.scene.shape.Rectangle;
import javafx.stage.Stage;
import xylixlike.engine.Level;

import static xylixlike.utils.FileOperations.loadLevel;

public class App extends Application {
    public static int SCALE = 32;

    public static void main(String[] args) {
        Application.launch();
    }

    @Override
    public void start(Stage primaryStage) {
        Level l = loadLevel("1");
        primaryStage.setScene(l.getScene());
        primaryStage.show();
    }
}
